import {
  CompositionPointerDemo,
  ConditionalDemo,
  ContextPointerDemo,
  EffectPointerDemo,
  EventsDemo,
  FormDemo,
  HooksPointerDemo,
  JsxDemo,
  ListDemo,
  PropsDemo,
  ReducerLikeDemo,
  RefDemo,
  RouterPointerDemo,
  StateDemo,
} from './demos'

export const lessons = [
  {
    slug: 'jsx',
    title: 'JSX',
    level: 'Base',
    summary: 'Écrire l’UI comme du HTML, avec du JavaScript dedans.',
    theory: [
      'JSX est une syntaxe qui compile vers React.createElement.',
      'Un composant retourne un arbre d’éléments. Une seule racine (ou un Fragment <>...</>).',
      'Les attributs HTML deviennent camelCase : className, onClick, htmlFor.',
      'Les expressions JS vont entre accolades : {user.name}, {items.length}.',
    ],
    Demo: JsxDemo,
  },
  {
    slug: 'composants-props',
    title: 'Composants et props',
    level: 'Base',
    summary: 'Découper l’UI en pièces réutilisables, paramétrées par des props.',
    theory: [
      'Un composant est une fonction qui reçoit des props et retourne du JSX.',
      'Les props descendent du parent vers l’enfant (données en lecture).',
      'On ne mute jamais une prop. Pour changer l’affichage, on change le state du parent.',
      'ProductCard dans le catalogue est un vrai composant à props.',
    ],
    Demo: PropsDemo,
  },
  {
    slug: 'state',
    title: 'State et useState',
    level: 'Base',
    summary: 'Mémoriser des données qui changent dans le temps.',
    theory: [
      'useState retourne [valeur, setValeur]. Un set relance le rendu du composant.',
      'Le state est local au composant. Pour le partager, on le remonte (lifting) ou on utilise Context.',
      'Quand le nouveau state dépend de l’ancien, utilise setCount(n => n + 1).',
      'Ne mute jamais le state : crée un nouvel objet / tableau.',
    ],
    Demo: StateDemo,
  },
  {
    slug: 'evenements',
    title: 'Événements',
    level: 'Base',
    summary: 'Réagir aux clics, saisies, soumissions.',
    theory: [
      'React utilise des événements synthétiques : onClick, onChange, onSubmit.',
      'On passe une fonction, on ne l’appelle pas : onClick={handleClick} et pas onClick={handleClick()}.',
      'e.preventDefault() empêche le rechargement d’un formulaire.',
    ],
    Demo: EventsDemo,
  },
  {
    slug: 'rendu-conditionnel',
    title: 'Rendu conditionnel',
    level: 'Base',
    summary: 'Afficher une UI différente selon l’état.',
    theory: [
      'Ternaire : {loading ? <Spinner /> : <List />}',
      'Court-circuit : {error && <p>{error.message}</p>}',
      'Retour anticipé : if (!user) return <Login />',
      'Les pages Produits / Recettes montrent loading, erreur et liste vide.',
    ],
    Demo: ConditionalDemo,
  },
  {
    slug: 'listes-keys',
    title: 'Listes et keys',
    level: 'Base',
    summary: 'Rendre un tableau d’éléments de façon stable.',
    theory: [
      'On mappe un tableau vers du JSX.',
      'Chaque élément de liste a besoin d’une key unique et stable (id, pas l’index si la liste bouge).',
      'La key aide React à réconcilier le DOM virtuel.',
    ],
    Demo: ListDemo,
  },
  {
    slug: 'formulaires',
    title: 'Formulaires contrôlés',
    level: 'Base',
    summary: 'Le state React est la source de vérité des champs.',
    theory: [
      'Un input contrôlé a value={state} et onChange qui met à jour le state.',
      'On peut gérer plusieurs champs avec un objet { name, value }.',
      'La page Connexion est un formulaire contrôlé branché sur DummyJSON.',
    ],
    Demo: FormDemo,
  },
  {
    slug: 'useeffect',
    title: 'useEffect et l’API',
    level: 'Intermédiaire',
    summary: 'Synchroniser React avec le monde extérieur (fetch, timers).',
    theory: [
      'useEffect(fn, deps) s’exécute après le rendu, si les deps changent.',
      '[] = une fois au montage. [query] = à chaque changement de query.',
      'Toujours nettoyer : abort d’un fetch, clearTimeout, cancelled = true.',
      'Le hook useFetch de ce projet encapsule loading / data / error.',
    ],
    Demo: EffectPointerDemo,
  },
  {
    slug: 'hooks-perso',
    title: 'Hooks personnalisés',
    level: 'Intermédiaire',
    summary: 'Réutiliser de la logique à état.',
    theory: [
      'Un custom hook est une fonction qui commence par use et appelle d’autres hooks.',
      'useFetch et useDebounce dans src/hooks/ sont les exemples du projet.',
      'Les hooks ne s’appellent pas dans des conditions ni des boucles (règles des hooks).',
    ],
    Demo: HooksPointerDemo,
  },
  {
    slug: 'context',
    title: 'Context API',
    level: 'Intermédiaire',
    summary: 'Partager un state sans passer des props à tous les étages.',
    theory: [
      'createContext + Provider + useContext.',
      'Ici : AuthContext (session DummyJSON) et CartContext (panier).',
      'À réserver aux données vraiment globales (auth, thème, panier). Sinon, props.',
    ],
    Demo: ContextPointerDemo,
  },
  {
    slug: 'useref',
    title: 'useRef',
    level: 'Intermédiaire',
    summary: 'Garder une boîte mutable (DOM ou valeur) sans re-render.',
    theory: [
      'ref.current est mutable. Le changer ne relance pas le rendu.',
      'Usage classique : focus un input, stocker un id de timer, garder la valeur précédente.',
    ],
    Demo: RefDemo,
  },
  {
    slug: 'memo',
    title: 'useMemo et useCallback',
    level: 'Avancé',
    summary: 'Éviter des calculs ou des fonctions recréées trop souvent.',
    theory: [
      'useMemo mémorise un calcul coûteux.',
      'useCallback mémorise une fonction (utile si un enfant est mémoïsé).',
      'AuthContext et CartContext utilisent useMemo pour stabiliser la value du Provider.',
      'Ne pas optimiser trop tôt : lisibilité d’abord.',
    ],
    Demo: ReducerLikeDemo,
  },
  {
    slug: 'usereducer',
    title: 'useReducer',
    level: 'Avancé',
    summary: 'State complexe mis à jour par des actions.',
    theory: [
      'dispatch({ type, payload }) → reducer(state, action) → nouveau state.',
      'Le panier (CartContext) est un reducer : ADD, REMOVE, CLEAR.',
      'Utile quand plusieurs mises à jour liées se marchent dessus avec useState.',
    ],
    Demo: ReducerLikeDemo,
  },
  {
    slug: 'composition',
    title: 'Composition (children)',
    level: 'Intermédiaire',
    summary: 'Assembler des composants comme des briques.',
    theory: [
      'props.children est le contenu entre les balises du composant.',
      'Layout, cartes, modales : on compose plutôt que d’hériter.',
      'React n’a pas d’héritage de classes UI : on compose.',
    ],
    Demo: CompositionPointerDemo,
  },
  {
    slug: 'router',
    title: 'React Router',
    level: 'Intermédiaire',
    summary: 'Plusieurs pages dans une Single Page Application.',
    theory: [
      'BrowserRouter, Routes, Route, Link, useParams, useNavigate, NavLink.',
      '/produits/:id lit l’id avec useParams puis fetch DummyJSON.',
      'ProtectedRoute redirige vers /connexion si pas de session.',
    ],
    Demo: RouterPointerDemo,
  },
]
